# based off: https://docs.mpcdf.mpg.de/doc/data/gitlab/devop-tutorial.html
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Cache settings to maintain any files downloaded by pip - saves it downloading requirements multiple times
cache:
  paths:
    - .cache/pip

# Define shared settings for all Python jobs
stages:
  - code_quality
  - test
  - build_and_deploy

before_script:
  - apt-get update && apt-get install -y git

.python_template:
  before_script:
    - apt-get update
    - python --version ; pip --version  # For debugging
    - pip install poetry
    - poetry config http-basic.gitlab_v2 "__token__" "$GITLAB_PROJECT_ACCESS"
    - poetry install
    - source `poetry env info --path`/bin/activate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  # Run when a merge request is created
    - if: '$CI_PIPELINE_SOURCE == "push"'  # Run when a commit is pushed

# Ruff/Black Linting Job
ruff_lint:
  stage: code_quality
  extends: .python_template
  image: "python:3.11"
  script:
    - poetry install --with checks
    - black .
    - ruff check

# SQL Fluff Linting Job
sql_lint:
  stage: code_quality
  extends: .python_template
  image: "python:3.11"
  script:
    - poetry install --with checks
    - sqlfluff lint .


# MyPy Type Checking Job
mypy_typecheck:
  stage: code_quality
  extends: .python_template
  image: "python:3.11"
  script:
    - poetry install --with checks
    - mypy --install-types --non-interactive .
  allow_failure: true

# Testing and Coverage Job with Coverage.py for Multiple Python Versions
run_tests:
  stage: test
  extends: .python_template
  script:
    - poetry install --with test
    - python gitlab_prep/set_keyring_from_env.py
    - coverage run -m unittest discover
    - coverage report  # Display coverage report in the job log
    - coverage xml     # Generate an XML report
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11"]
  image: "python:${PYTHON_VERSION}"
  coverage: '/TOTAL.*\s+(\d+\%)$/'  # Regular expression to capture coverage percentage
  artifacts:
    paths:
      - coverage.xml

test_snowflake:
  stage: test
  extends: .python_template
  image: "python:3.11"
  script:
    - poetry install --with test
    - python gitlab_prep/snowflake_check_deploy.py
  rules:
    - changes:
        - snowflake_views/**/*  # only run when there are changes in the snowflake_views folder

# Snowflake Feature -> Dev Deployment
snowflake_dev_deploy:
  stage: build_and_deploy
  extends: .python_template
  image: 'python:3.11'
  script:
    - poetry install --with build
    - python gitlab_prep/set_keyring_from_env.py
    - python gitlab_prep/snowflake_deploy.py --env dev
  rules:
   - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PROJECT_NAME != "new-project-template"'
     changes:
       - snowflake_views/**/*  # only run when there are changes in the snowflake_views folder
   - when: never


# Snowflake Dev -> Prod Deployment
snowflake_prod_deploy:
  stage: build_and_deploy
  extends: .python_template
  image: 'python:3.11'
  script:
    - poetry install --with build
    - python gitlab_prep/set_keyring_from_env.py
    - python gitlab_prep/snowflake_deploy.py --env prod
  rules:
   - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_NAME != "new-project-template"'
     changes:
       - snowflake_views/**/*  # only run when there are changes in the snowflake_views folder
   - when: never
