# based off: https://docs.mpcdf.mpg.de/doc/data/gitlab/devop-tutorial.html
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Cache settings to maintain any files downloaded by pip - saves it downloading requirements multiple times
cache:
  paths:
    - .cache/pip

# Define shared settings for all Python jobs
stages:
  - code_quality
  - test
  - build_and_deploy

before_script:
  - apt-get update && apt-get install -y git

include:
  - project: 'data-and-insights/tem/gitlab-cicd-templates'
    file: '/templates/.python_template.yml'
    ref: main
  - project: 'data-and-insights/tem/gitlab-cicd-templates'
    file: '/templates/.build_and_deploy.yml'
    ref: main

# Ruff/Black Linting Job
ruff_lint:
  stage: code_quality
  extends: .python_template
  image: "python:3.11"
  script:
    - poetry install --with checks
    - black .
    - ruff check
  allow_failure: true  # Keeps the pipeline running even if this fails

# MyPy Type Checking Job
mypy_typecheck:
  stage: code_quality
  extends: .python_template
  image: "python:3.11"
  script:
    - poetry install --with checks
    - mypy --install-types --non-interactive .
  allow_failure: true

# Testing and Coverage Job with Coverage.py for Multiple Python Versions
run_tests:
  stage: test
  extends: .python_template
  script:
    - poetry install --with test
    - python gitlab_prep/set_keyring_from_env.py
    - coverage run -m unittest discover
    - coverage report  # Display coverage report in the job log
    - coverage xml     # Generate an XML report
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11", "3.12"]
  image: "python:${PYTHON_VERSION}"
  coverage: '/TOTAL.*\s+(\d+\%)$/'  # Regular expression to capture coverage percentage
  artifacts:
    paths:
      - coverage.xml

# # Build and Deploy Job
# build_and_deploy:
#   stage: build_and_deploy
#   image: 'python:3.11'
#   extends: .build_and_deploy
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
