CREATE OR REPLACE VIEW CLIENT_DB.BASE_DEV.SALESFORCE_OPPORTUNITY AS
SELECT
    ID,
    NAME,
    STAGE_NAME,
    CLOSE_DATE
FROM CLIENT_DB.SALESFORCE_PROD.OPPORTUNITY
WHERE _FIVETRAN_DELETED = FALSE AND IS_DELETED = FALSE;
