CREATE OR REPLACE VIEW CLIENT_DB.BASE_DEV.SALESFORCE_LEAD_ALL AS
SELECT
    -- STANDARD FIELDS
    ID,
    RECORD_TYPE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    STATUS,
    LEAD_SOURCE,
    COUNTRY,
    COMPANY,
    CREATED_DATE,
    LAST_MODIFIED_DATE,
    CONVERTED_DATE,
    OWNER_ID,

    -- CONVERSION IDs
    CONVERTED_CONTACT_ID,
    CONVERTED_ACCOUNT_ID,
    CONVERTED_OPPORTUNITY_ID

FROM CLIENT_DB.SALESFORCE_PROD.LEAD
WHERE _FIVETRAN_DELETED = FALSE AND IS_DELETED = FALSE;
