CREATE OR REPLACE VIEW AVIS_DB.BASE_DEV.SALESFORCE_LEAD_CONVERTED AS
SELECT
    ID,
    EMAIL
FROM AVIS_DB.SALESFORCE_PROD.LEAD
WHERE _FIVETRAN_DELETED = FALSE AND IS_DELETED = FALSE AND IS_CONVERTED = TRUE;
