USE ROLE CLIENT_ROLE;

CREATE OR REPLACE VIEW CLIENT_DB.BASE_DEV.SALESFORCE_LEAD_CONVERTED AS
SELECT
    ID,
    EMAIL
FROM CLIENT_DB.SALESFORCE_PROD.LEAD
WHERE _FIVETRAN_DELETED = FALSE AND IS_DELETED = FALSE AND IS_CONVERTED = TRUE;
