USE ROLE CLIENT_DB;

CREATE OR REPLACE VIEW CLIENT_DB.BASE_DEV.SALESFORCE_OPPORTUNITY AS
SELECT
    ID,
    NAME,
    STAGE_NAME,
    SEAM_POTENTIAL_REVENUE_PER_YEAR_C AS TOTAL_POTENTIAL_REVENUE_PER_YEAR,
    --     ACTUAL_FULL_YEAR_PY_REVENUE_C as ACTUAL_FULL_YEAR_PY_REVENUE, (Account.Annual_Revenue_PY__c in Salesforce)
    --     ACTUAL_YTD_PY_REVENUE_C  as ACTUAL_YTD_PY_REVENUE (Account.SEAM_YTD_1_RRR__c)
    --     ACTUAL_YT_CY_REVENUE_C  as ACTUAL_YT_CY_REVENUE (Account.SEAM_YTD_RRR__c)
    CLOSE_DATE
FROM CLIENT_DB.SALESFORCE_PROD.OPPORTUNITY
WHERE _FIVETRAN_DELETED = FALSE AND IS_DELETED = FALSE;
