USE ROLE CLIENT_ROLE;

CREATE OR REPLACE VIEW CLIENT_DB.DASHBOARDS_MARKETING_DEV.LEADS_CONVERTED AS

SELECT
    -- basic fields
    PWCD.LEAD_ID,
    PWCD.COUNTRY,
    PWCD.MAPPED_COUNTRY,
    PWCD.AE_CAMPAIGN,
    PWCD.GROUPED_CAMPAIGN,
    PWCD.AE_FIRST_REFERRER_TYPE,
    PWCD.STATUS,

    -- opp fields
    PWCD.STAGE_NAME                                          AS OPPORTUNITY_STAGE_NAME,
    PWCD.TOTAL_POTENTIAL_REVENUE_PER_YEAR                    AS OPPORTUNITY_POTENTIAL_REVENUE_PER_YEAR,

    -- date calculations
    PWCD.CREATED_DATE,
    PWCD.CONVERTED_DATE,
    DATEDIFF('hour', PWCD.CREATED_DATE, PWCD.CONVERTED_DATE) AS LEAD_CONVERSION_HOURS
FROM CLIENT_DB.INTERMEDIATE_DEV.PERSON_WITH_CONVERSION_DETAILS AS PWCD

WHERE PWCD.RECORD_TYPE_ID IN (
        '012300000000O2tAAE', -- Europe
        '01240000000MJhjAAG', -- EMEA Web Leads
        '01240000000QM5nAAG' -- EMEA Telesales
    );
